/** Generated by YAKINDU Statechart Tools code generator. */


#include "sc_types.h"

#include "MqttClientStatemachine.h"
#include "MqttClientStatemachine_required.h"

/*! \file Implementation of the state machine 'MqttClientStatemachine'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void effect_main_region_Offline_tr0(MqttClientStatemachine* handle);
static void enact_main_region_Online_r1_Wait(MqttClientStatemachine* handle);
static void enact_main_region_Offline_r1_Ready(MqttClientStatemachine* handle);
static void exact_main_region_Online_r1_Wait(MqttClientStatemachine* handle);
static void exact_main_region_Offline_r1_Ready(MqttClientStatemachine* handle);
static void enseq_main_region_Online_default(MqttClientStatemachine* handle);
static void enseq_main_region_Online_r1_ConnectToBroker_default(MqttClientStatemachine* handle);
static void enseq_main_region_Online_r1_Ready_default(MqttClientStatemachine* handle);
static void enseq_main_region_Online_r1_PublishTopic_default(MqttClientStatemachine* handle);
static void enseq_main_region_Online_r1_Wait_default(MqttClientStatemachine* handle);
static void enseq_main_region_Online_r1_DisconnectFromBroker_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_WifiConnectionLost(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_SetTopic_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_Ready_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_SetStationMode_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_ConfigureMqtt_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_ConfigureDhcp_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_ConnectToAccesspoint_default(MqttClientStatemachine* handle);
static void enseq_main_region_default(MqttClientStatemachine* handle);
static void enseq_main_region_Online_r1_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_WifiConnectionLost(MqttClientStatemachine* handle);
static void exseq_main_region_Online(MqttClientStatemachine* handle);
static void exseq_main_region_Online_r1_ConnectToBroker(MqttClientStatemachine* handle);
static void exseq_main_region_Online_r1_Ready(MqttClientStatemachine* handle);
static void exseq_main_region_Online_r1_PublishTopic(MqttClientStatemachine* handle);
static void exseq_main_region_Online_r1_Wait(MqttClientStatemachine* handle);
static void exseq_main_region_Online_r1_DisconnectFromBroker(MqttClientStatemachine* handle);
static void exseq_main_region_Offline(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1_SetTopic(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1_Ready(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1_SetStationMode(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1_ConfigureMqtt(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1_ConfigureDhcp(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1_ConnectToAccesspoint(MqttClientStatemachine* handle);
static void exseq_main_region(MqttClientStatemachine* handle);
static void exseq_main_region_Online_r1(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1(MqttClientStatemachine* handle);
static void react_main_region_Online_r1__entry_Default(MqttClientStatemachine* handle);
static void react_main_region_Offline_r1__entry_Default(MqttClientStatemachine* handle);
static void react_main_region_Offline_r1_WifiConnectionLost(MqttClientStatemachine* handle);
static void react_main_region__entry_Default(MqttClientStatemachine* handle);
static void react_main_region_Offline_r1_WifiConnectionEstablished(MqttClientStatemachine* handle);

/*! State machine reactions. */
static sc_integer react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Online. */
static sc_integer main_region_Online_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state ConnectToBroker. */
static sc_integer main_region_Online_r1_ConnectToBroker_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Ready. */
static sc_integer main_region_Online_r1_Ready_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state PublishTopic. */
static sc_integer main_region_Online_r1_PublishTopic_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Wait. */
static sc_integer main_region_Online_r1_Wait_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state DisconnectFromBroker. */
static sc_integer main_region_Online_r1_DisconnectFromBroker_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Offline. */
static sc_integer main_region_Offline_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state SetTopic. */
static sc_integer main_region_Offline_r1_SetTopic_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Ready. */
static sc_integer main_region_Offline_r1_Ready_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state SetStationMode. */
static sc_integer main_region_Offline_r1_SetStationMode_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state ConfigureMqtt. */
static sc_integer main_region_Offline_r1_ConfigureMqtt_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state ConfigureDhcp. */
static sc_integer main_region_Offline_r1_ConfigureDhcp_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state ConnectToAccesspoint. */
static sc_integer main_region_Offline_r1_ConnectToAccesspoint_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);


static void clear_out_events(MqttClientStatemachine* handle);

static void swap_in_events(MqttClientStatemachine* handle);

static void clear_in_events(MqttClientStatemachine* handle);

static void micro_step(MqttClientStatemachine* handle);





void mqttClientStatemachine_init(MqttClientStatemachine* handle)
{
	sc_integer i;
	
	for (i = 0; i < MQTTCLIENTSTATEMACHINE_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = MqttClientStatemachine_last_state;
	}
	
				
	clear_in_events(handle);
	swap_in_events(handle);
	clear_out_events(handle);
	
	sc_observable_init(&handle->ifaceWizFi360.setStationMode);
	sc_observable_init(&handle->ifaceWizFi360.configureDhcp);
	sc_observable_init(&handle->ifaceWizFi360.connectToAccessPoint);
	sc_observable_init(&handle->ifaceWizFi360.configureMqtt);
	sc_observable_init(&handle->ifaceWizFi360.setTopic);
	sc_observable_init(&handle->ifaceWizFi360.connectToBroker);
	sc_observable_init(&handle->ifaceWizFi360.disconnectFromBroker);
	sc_observable_init(&handle->ifaceWizFi360.publishTopic);
	
	/* Default init sequence for statechart MqttClientStatemachine */
	handle->iface.dT = 200;
	handle->iface.publishInterval = 1000;
	handle->ifaceWizFi360.wifiConnected = bool_false;
	
	handle->isExecuting = bool_false;
}

void mqttClientStatemachine_run_cycle(MqttClientStatemachine* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	clear_out_events(handle);
	swap_in_events(handle);
	micro_step(handle);
	handle->isExecuting = bool_false;
}

void mqttClientStatemachine_enter(MqttClientStatemachine* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart MqttClientStatemachine */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void mqttClientStatemachine_exit(MqttClientStatemachine* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart MqttClientStatemachine */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}


sc_boolean mqttClientStatemachine_is_active(const MqttClientStatemachine* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < MQTTCLIENTSTATEMACHINE_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != MqttClientStatemachine_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean mqttClientStatemachine_is_final(const MqttClientStatemachine* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

void mqttClientStatemachine_raise_time_event(MqttClientStatemachine* handle, sc_eventid evid)
{
	if ( ((sc_intptr_t)evid) >= ((sc_intptr_t)&(handle->timeEvents))
		&&  ((sc_intptr_t)evid) < ((sc_intptr_t)&(handle->timeEvents)) + (unsigned)sizeof(MqttClientStatemachineTimeEvents))
		{
		*(sc_boolean*)evid = bool_true;
	}
}

sc_boolean mqttClientStatemachine_is_state_active(const MqttClientStatemachine* handle, MqttClientStatemachineStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case MqttClientStatemachine_main_region_Online :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE] >= MqttClientStatemachine_main_region_Online
				&& handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE] <= MqttClientStatemachine_main_region_Online_r1_DisconnectFromBroker);
			break;
		case MqttClientStatemachine_main_region_Online_r1_ConnectToBroker :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE_R1_CONNECTTOBROKER] == MqttClientStatemachine_main_region_Online_r1_ConnectToBroker
			);
			break;
		case MqttClientStatemachine_main_region_Online_r1_Ready :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE_R1_READY] == MqttClientStatemachine_main_region_Online_r1_Ready
			);
			break;
		case MqttClientStatemachine_main_region_Online_r1_PublishTopic :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE_R1_PUBLISHTOPIC] == MqttClientStatemachine_main_region_Online_r1_PublishTopic
			);
			break;
		case MqttClientStatemachine_main_region_Online_r1_Wait :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE_R1_WAIT] == MqttClientStatemachine_main_region_Online_r1_Wait
			);
			break;
		case MqttClientStatemachine_main_region_Online_r1_DisconnectFromBroker :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE_R1_DISCONNECTFROMBROKER] == MqttClientStatemachine_main_region_Online_r1_DisconnectFromBroker
			);
			break;
		case MqttClientStatemachine_main_region_Offline :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE] >= MqttClientStatemachine_main_region_Offline
				&& handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE] <= MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint);
			break;
		case MqttClientStatemachine_main_region_Offline_r1_SetTopic :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE_R1_SETTOPIC] == MqttClientStatemachine_main_region_Offline_r1_SetTopic
			);
			break;
		case MqttClientStatemachine_main_region_Offline_r1_Ready :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE_R1_READY] == MqttClientStatemachine_main_region_Offline_r1_Ready
			);
			break;
		case MqttClientStatemachine_main_region_Offline_r1_SetStationMode :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE_R1_SETSTATIONMODE] == MqttClientStatemachine_main_region_Offline_r1_SetStationMode
			);
			break;
		case MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE_R1_CONFIGUREMQTT] == MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt
			);
			break;
		case MqttClientStatemachine_main_region_Offline_r1_ConfigureDhcp :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE_R1_CONFIGUREDHCP] == MqttClientStatemachine_main_region_Offline_r1_ConfigureDhcp
			);
			break;
		case MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE_R1_CONNECTTOACCESSPOINT] == MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clear_out_events(MqttClientStatemachine* handle)
{
	handle->ifaceWizFi360.setStationMode_raised = bool_false;
	handle->ifaceWizFi360.configureDhcp_raised = bool_false;
	handle->ifaceWizFi360.connectToAccessPoint_raised = bool_false;
	handle->ifaceWizFi360.configureMqtt_raised = bool_false;
	handle->ifaceWizFi360.setTopic_raised = bool_false;
	handle->ifaceWizFi360.connectToBroker_raised = bool_false;
	handle->ifaceWizFi360.disconnectFromBroker_raised = bool_false;
	handle->ifaceWizFi360.publishTopic_raised = bool_false;
}

static void swap_in_events(MqttClientStatemachine* handle)
{
	handle->current.ifaceWizFi360.ok_raised = handle->ifaceWizFi360.ok_raised;
	handle->ifaceWizFi360.ok_raised = bool_false;
	handle->current.ifaceWizFi360.error_raised = handle->ifaceWizFi360.error_raised;
	handle->ifaceWizFi360.error_raised = bool_false;
	handle->current.ifaceWizFi360.fail_raised = handle->ifaceWizFi360.fail_raised;
	handle->ifaceWizFi360.fail_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Online_r1_Wait_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_Wait_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_Wait_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_Ready_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_Ready_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_Ready_tev0_raised = bool_false;
}

static void clear_in_events(MqttClientStatemachine* handle)
{
	handle->ifaceWizFi360.ok_raised = bool_false;
	handle->ifaceWizFi360.error_raised = bool_false;
	handle->ifaceWizFi360.fail_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_Wait_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_Ready_tev0_raised = bool_false;
}

static void micro_step(MqttClientStatemachine* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case MqttClientStatemachine_main_region_Online_r1_ConnectToBroker :
		{
			main_region_Online_r1_ConnectToBroker_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_Ready :
		{
			main_region_Online_r1_Ready_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_PublishTopic :
		{
			main_region_Online_r1_PublishTopic_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_Wait :
		{
			main_region_Online_r1_Wait_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_DisconnectFromBroker :
		{
			main_region_Online_r1_DisconnectFromBroker_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_SetTopic :
		{
			main_region_Offline_r1_SetTopic_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_Ready :
		{
			main_region_Offline_r1_Ready_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_SetStationMode :
		{
			main_region_Offline_r1_SetStationMode_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt :
		{
			main_region_Offline_r1_ConfigureMqtt_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConfigureDhcp :
		{
			main_region_Offline_r1_ConfigureDhcp_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint :
		{
			main_region_Offline_r1_ConnectToAccesspoint_react(handle, -1);
			break;
		}
		default: break;
	}
}




sc_integer mqttClientStatemachine_get_dT(const MqttClientStatemachine* handle)
{
	return handle->iface.dT;
}
void mqttClientStatemachine_set_dT(MqttClientStatemachine* handle, sc_integer value)
{
	handle->iface.dT = value;
}
sc_integer mqttClientStatemachine_get_publishInterval(const MqttClientStatemachine* handle)
{
	return handle->iface.publishInterval;
}
void mqttClientStatemachine_set_publishInterval(MqttClientStatemachine* handle, sc_integer value)
{
	handle->iface.publishInterval = value;
}
void mqttClientStatemachine_WizFi360_raise_ok(MqttClientStatemachine* handle)
{
	handle->ifaceWizFi360.ok_raised = bool_true;
}

void mqttClientStatemachine_WizFi360_raise_error(MqttClientStatemachine* handle)
{
	handle->ifaceWizFi360.error_raised = bool_true;
}

void mqttClientStatemachine_WizFi360_raise_fail(MqttClientStatemachine* handle)
{
	handle->ifaceWizFi360.fail_raised = bool_true;
}


sc_observable* mqttClientStatemachine_WizFi360_get_setStationMode(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.setStationMode;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_setStationMode(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.setStationMode_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_configureDhcp(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.configureDhcp;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_configureDhcp(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.configureDhcp_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_connectToAccessPoint(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.connectToAccessPoint;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_connectToAccessPoint(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.connectToAccessPoint_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_configureMqtt(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.configureMqtt;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_configureMqtt(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.configureMqtt_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_setTopic(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.setTopic;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_setTopic(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.setTopic_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_connectToBroker(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.connectToBroker;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_connectToBroker(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.connectToBroker_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_disconnectFromBroker(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.disconnectFromBroker;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_disconnectFromBroker(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.disconnectFromBroker_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_publishTopic(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.publishTopic;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_publishTopic(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.publishTopic_raised;
}

sc_boolean mqttClientStatemachine_WizFi360_get_wifiConnected(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.wifiConnected;
}
void mqttClientStatemachine_WizFi360_set_wifiConnected(MqttClientStatemachine* handle, sc_boolean value)
{
	handle->ifaceWizFi360.wifiConnected = value;
}

/* implementations of all internal functions */

static void effect_main_region_Offline_tr0(MqttClientStatemachine* handle)
{
	exseq_main_region_Offline(handle);
	enseq_main_region_Online_default(handle);
	react(handle, 0);
}

/* Entry action for state 'Wait'. */
static void enact_main_region_Online_r1_Wait(MqttClientStatemachine* handle)
{
	/* Entry action for state 'Wait'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_Wait_tev0_raised) , ((handle->iface.publishInterval - (2 * handle->iface.dT))), bool_false);
}

/* Entry action for state 'Ready'. */
static void enact_main_region_Offline_r1_Ready(MqttClientStatemachine* handle)
{
	/* Entry action for state 'Ready'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_Ready_tev0_raised) , (1 * 1000), bool_false);
}

/* Exit action for state 'Wait'. */
static void exact_main_region_Online_r1_Wait(MqttClientStatemachine* handle)
{
	/* Exit action for state 'Wait'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_Wait_tev0_raised) );		
}

/* Exit action for state 'Ready'. */
static void exact_main_region_Offline_r1_Ready(MqttClientStatemachine* handle)
{
	/* Exit action for state 'Ready'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_Ready_tev0_raised) );		
}

/* 'default' enter sequence for state Online */
static void enseq_main_region_Online_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Online */
	enseq_main_region_Online_r1_default(handle);
}

/* 'default' enter sequence for state ConnectToBroker */
static void enseq_main_region_Online_r1_ConnectToBroker_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state ConnectToBroker */
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Online_r1_ConnectToBroker;
}

/* 'default' enter sequence for state Ready */
static void enseq_main_region_Online_r1_Ready_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Ready */
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Online_r1_Ready;
}

/* 'default' enter sequence for state PublishTopic */
static void enseq_main_region_Online_r1_PublishTopic_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state PublishTopic */
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Online_r1_PublishTopic;
}

/* 'default' enter sequence for state Wait */
static void enseq_main_region_Online_r1_Wait_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Wait */
	enact_main_region_Online_r1_Wait(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Online_r1_Wait;
}

/* 'default' enter sequence for state DisconnectFromBroker */
static void enseq_main_region_Online_r1_DisconnectFromBroker_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state DisconnectFromBroker */
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Online_r1_DisconnectFromBroker;
}

/* 'WifiConnectionLost' enter sequence for state Offline */
static void enseq_main_region_Offline_WifiConnectionLost(MqttClientStatemachine* handle)
{
	/* 'WifiConnectionLost' enter sequence for state Offline */
	enseq_main_region_Offline_r1_WifiConnectionLost(handle);
}

/* 'default' enter sequence for state Offline */
static void enseq_main_region_Offline_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Offline */
	enseq_main_region_Offline_r1_default(handle);
}

/* 'default' enter sequence for state SetTopic */
static void enseq_main_region_Offline_r1_SetTopic_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state SetTopic */
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Offline_r1_SetTopic;
}

/* 'default' enter sequence for state Ready */
static void enseq_main_region_Offline_r1_Ready_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Ready */
	enact_main_region_Offline_r1_Ready(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Offline_r1_Ready;
}

/* 'default' enter sequence for state SetStationMode */
static void enseq_main_region_Offline_r1_SetStationMode_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state SetStationMode */
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Offline_r1_SetStationMode;
}

/* 'default' enter sequence for state ConfigureMqtt */
static void enseq_main_region_Offline_r1_ConfigureMqtt_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state ConfigureMqtt */
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt;
}

/* 'default' enter sequence for state ConfigureDhcp */
static void enseq_main_region_Offline_r1_ConfigureDhcp_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state ConfigureDhcp */
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Offline_r1_ConfigureDhcp;
}

/* 'default' enter sequence for state ConnectToAccesspoint */
static void enseq_main_region_Offline_r1_ConnectToAccesspoint_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state ConnectToAccesspoint */
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_Online_r1_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_Online_r1__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_Offline_r1_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_Offline_r1__entry_Default(handle);
}

/* 'WifiConnectionLost' enter sequence for region r1 */
static void enseq_main_region_Offline_r1_WifiConnectionLost(MqttClientStatemachine* handle)
{
	/* 'WifiConnectionLost' enter sequence for region r1 */
	react_main_region_Offline_r1_WifiConnectionLost(handle);
}

/* Default exit sequence for state Online */
static void exseq_main_region_Online(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Online */
	exseq_main_region_Online_r1(handle);
}

/* Default exit sequence for state ConnectToBroker */
static void exseq_main_region_Online_r1_ConnectToBroker(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state ConnectToBroker */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
}

/* Default exit sequence for state Ready */
static void exseq_main_region_Online_r1_Ready(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Ready */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
}

/* Default exit sequence for state PublishTopic */
static void exseq_main_region_Online_r1_PublishTopic(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state PublishTopic */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
}

/* Default exit sequence for state Wait */
static void exseq_main_region_Online_r1_Wait(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Wait */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Online_r1_Wait(handle);
}

/* Default exit sequence for state DisconnectFromBroker */
static void exseq_main_region_Online_r1_DisconnectFromBroker(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state DisconnectFromBroker */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
}

/* Default exit sequence for state Offline */
static void exseq_main_region_Offline(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Offline */
	exseq_main_region_Offline_r1(handle);
}

/* Default exit sequence for state SetTopic */
static void exseq_main_region_Offline_r1_SetTopic(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state SetTopic */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
}

/* Default exit sequence for state Ready */
static void exseq_main_region_Offline_r1_Ready(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Ready */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Offline_r1_Ready(handle);
}

/* Default exit sequence for state SetStationMode */
static void exseq_main_region_Offline_r1_SetStationMode(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state SetStationMode */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
}

/* Default exit sequence for state ConfigureMqtt */
static void exseq_main_region_Offline_r1_ConfigureMqtt(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state ConfigureMqtt */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
}

/* Default exit sequence for state ConfigureDhcp */
static void exseq_main_region_Offline_r1_ConfigureDhcp(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state ConfigureDhcp */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
}

/* Default exit sequence for state ConnectToAccesspoint */
static void exseq_main_region_Offline_r1_ConnectToAccesspoint(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state ConnectToAccesspoint */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
}

/* Default exit sequence for region main region */
static void exseq_main_region(MqttClientStatemachine* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of MqttClientStatemachine.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case MqttClientStatemachine_main_region_Online_r1_ConnectToBroker :
		{
			exseq_main_region_Online_r1_ConnectToBroker(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_Ready :
		{
			exseq_main_region_Online_r1_Ready(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_PublishTopic :
		{
			exseq_main_region_Online_r1_PublishTopic(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_Wait :
		{
			exseq_main_region_Online_r1_Wait(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_DisconnectFromBroker :
		{
			exseq_main_region_Online_r1_DisconnectFromBroker(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_SetTopic :
		{
			exseq_main_region_Offline_r1_SetTopic(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_Ready :
		{
			exseq_main_region_Offline_r1_Ready(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_SetStationMode :
		{
			exseq_main_region_Offline_r1_SetStationMode(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt :
		{
			exseq_main_region_Offline_r1_ConfigureMqtt(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConfigureDhcp :
		{
			exseq_main_region_Offline_r1_ConfigureDhcp(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint :
		{
			exseq_main_region_Offline_r1_ConnectToAccesspoint(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_main_region_Online_r1(MqttClientStatemachine* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of MqttClientStatemachine.main_region.Online.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case MqttClientStatemachine_main_region_Online_r1_ConnectToBroker :
		{
			exseq_main_region_Online_r1_ConnectToBroker(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_Ready :
		{
			exseq_main_region_Online_r1_Ready(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_PublishTopic :
		{
			exseq_main_region_Online_r1_PublishTopic(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_Wait :
		{
			exseq_main_region_Online_r1_Wait(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_DisconnectFromBroker :
		{
			exseq_main_region_Online_r1_DisconnectFromBroker(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_main_region_Offline_r1(MqttClientStatemachine* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of MqttClientStatemachine.main_region.Offline.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case MqttClientStatemachine_main_region_Offline_r1_SetTopic :
		{
			exseq_main_region_Offline_r1_SetTopic(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_Ready :
		{
			exseq_main_region_Offline_r1_Ready(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_SetStationMode :
		{
			exseq_main_region_Offline_r1_SetStationMode(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt :
		{
			exseq_main_region_Offline_r1_ConfigureMqtt(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConfigureDhcp :
		{
			exseq_main_region_Offline_r1_ConfigureDhcp(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint :
		{
			exseq_main_region_Offline_r1_ConnectToAccesspoint(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region_Online_r1__entry_Default(MqttClientStatemachine* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Online_r1_Ready_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_Offline_r1__entry_Default(MqttClientStatemachine* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Offline_r1_Ready_default(handle);
}

/* Default react sequence for initial entry WifiConnectionLost */
static void react_main_region_Offline_r1_WifiConnectionLost(MqttClientStatemachine* handle)
{
	/* Default react sequence for initial entry WifiConnectionLost */
	enseq_main_region_Offline_r1_ConnectToAccesspoint_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(MqttClientStatemachine* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Offline_default(handle);
}

/* The reactions of exit WifiConnectionEstablished. */
static void react_main_region_Offline_r1_WifiConnectionEstablished(MqttClientStatemachine* handle)
{
	/* The reactions of exit WifiConnectionEstablished. */
	effect_main_region_Offline_tr0(handle);
}


static sc_integer react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer main_region_Online_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Online. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->ifaceWizFi360.wifiConnected == bool_false)
		{ 
			exseq_main_region_Online(handle);
			enseq_main_region_Offline_WifiConnectionLost(handle);
			react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Online_r1_ConnectToBroker_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ConnectToBroker. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Online_r1_ConnectToBroker(handle);
			sc_observable_next(&handle->ifaceWizFi360.publishTopic);
			handle->ifaceWizFi360.publishTopic_raised = bool_true;
			enseq_main_region_Online_r1_PublishTopic_default(handle);
			main_region_Online_react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Online_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Online_r1_Ready_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Ready. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		exseq_main_region_Online_r1_Ready(handle);
		sc_observable_next(&handle->ifaceWizFi360.connectToBroker);
		handle->ifaceWizFi360.connectToBroker_raised = bool_true;
		enseq_main_region_Online_r1_ConnectToBroker_default(handle);
		main_region_Online_react(handle, 0);
		transitioned_after = 0;
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Online_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Online_r1_PublishTopic_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state PublishTopic. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Online_r1_PublishTopic(handle);
			enseq_main_region_Online_r1_Wait_default(handle);
			main_region_Online_react(handle, 0);
			transitioned_after = 0;
		}  else
		{
			if (handle->current.ifaceWizFi360.error_raised == bool_true)
			{ 
				exseq_main_region_Online_r1_PublishTopic(handle);
				sc_observable_next(&handle->ifaceWizFi360.disconnectFromBroker);
				handle->ifaceWizFi360.disconnectFromBroker_raised = bool_true;
				enseq_main_region_Online_r1_DisconnectFromBroker_default(handle);
				main_region_Online_react(handle, 0);
				transitioned_after = 0;
			} 
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Online_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Online_r1_Wait_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Wait. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.timeEvents.MqttClientStatemachine_main_region_Online_r1_Wait_time_event_0_raised == bool_true)
		{ 
			exseq_main_region_Online_r1_Wait(handle);
			sc_observable_next(&handle->ifaceWizFi360.publishTopic);
			handle->ifaceWizFi360.publishTopic_raised = bool_true;
			enseq_main_region_Online_r1_PublishTopic_default(handle);
			main_region_Online_react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Online_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Online_r1_DisconnectFromBroker_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state DisconnectFromBroker. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Online_r1_DisconnectFromBroker(handle);
			sc_observable_next(&handle->ifaceWizFi360.connectToBroker);
			handle->ifaceWizFi360.connectToBroker_raised = bool_true;
			enseq_main_region_Online_r1_ConnectToBroker_default(handle);
			main_region_Online_react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Online_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Offline. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_r1_SetTopic_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state SetTopic. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Offline_r1_SetTopic(handle);
			sc_observable_next(&handle->ifaceWizFi360.connectToAccessPoint);
			handle->ifaceWizFi360.connectToAccessPoint_raised = bool_true;
			enseq_main_region_Offline_r1_ConnectToAccesspoint_default(handle);
			main_region_Offline_react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Offline_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_r1_Ready_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Ready. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_Ready_time_event_0_raised == bool_true)
		{ 
			exseq_main_region_Offline_r1_Ready(handle);
			sc_observable_next(&handle->ifaceWizFi360.setStationMode);
			handle->ifaceWizFi360.setStationMode_raised = bool_true;
			enseq_main_region_Offline_r1_SetStationMode_default(handle);
			main_region_Offline_react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Offline_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_r1_SetStationMode_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state SetStationMode. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Offline_r1_SetStationMode(handle);
			sc_observable_next(&handle->ifaceWizFi360.configureDhcp);
			handle->ifaceWizFi360.configureDhcp_raised = bool_true;
			enseq_main_region_Offline_r1_ConfigureDhcp_default(handle);
			main_region_Offline_react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Offline_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_r1_ConfigureMqtt_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ConfigureMqtt. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Offline_r1_ConfigureMqtt(handle);
			sc_observable_next(&handle->ifaceWizFi360.setTopic);
			handle->ifaceWizFi360.setTopic_raised = bool_true;
			enseq_main_region_Offline_r1_SetTopic_default(handle);
			main_region_Offline_react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Offline_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_r1_ConfigureDhcp_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ConfigureDhcp. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Offline_r1_ConfigureDhcp(handle);
			sc_observable_next(&handle->ifaceWizFi360.configureMqtt);
			handle->ifaceWizFi360.configureMqtt_raised = bool_true;
			enseq_main_region_Offline_r1_ConfigureMqtt_default(handle);
			main_region_Offline_react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Offline_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_r1_ConnectToAccesspoint_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ConnectToAccesspoint. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->current.ifaceWizFi360.ok_raised) == bool_true) && ((handle->ifaceWizFi360.wifiConnected) == bool_true))
		{ 
			exseq_main_region_Offline_r1_ConnectToAccesspoint(handle);
			react_main_region_Offline_r1_WifiConnectionEstablished(handle);
			transitioned_after = 0;
		}  else
		{
			if (((handle->current.ifaceWizFi360.fail_raised) == bool_true) && ((!handle->ifaceWizFi360.wifiConnected) == bool_true))
			{ 
				exseq_main_region_Offline_r1_ConnectToAccesspoint(handle);
				sc_observable_next(&handle->ifaceWizFi360.connectToAccessPoint);
				handle->ifaceWizFi360.connectToAccessPoint_raised = bool_true;
				enseq_main_region_Offline_r1_ConnectToAccesspoint_default(handle);
				main_region_Offline_react(handle, 0);
				transitioned_after = 0;
			} 
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Offline_react(handle, transitioned_before);
	} return transitioned_after;
}




