/** Generated by YAKINDU Statechart Tools code generator. */


#include "sc_types.h"

#include "MqttClientStatemachine.h"
#include "MqttClientStatemachine_required.h"

/*! \file Implementation of the state machine 'MqttClientStatemachine'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static sc_boolean check_main_region_Undefined_r1__choice_0_tr1_tr1(MqttClientStatemachine* handle);
static sc_boolean check_main_region_Undefined_r1__choice_2_tr1_tr1(MqttClientStatemachine* handle);
static sc_boolean check_main_region_Undefined_r1__choice_5_tr1_tr1(MqttClientStatemachine* handle);
static void effect_main_region_Undefined_tr0(MqttClientStatemachine* handle);
static void effect_main_region_Online_tr1(MqttClientStatemachine* handle);
static void effect_main_region_Offline_tr0(MqttClientStatemachine* handle);
static void effect_main_region_Offline_tr1(MqttClientStatemachine* handle);
static void effect_main_region_Undefined_r1__choice_0_tr1(MqttClientStatemachine* handle);
static void effect_main_region_Undefined_r1__choice_0_tr0(MqttClientStatemachine* handle);
static void effect_main_region_Undefined_r1__choice_1_tr0(MqttClientStatemachine* handle);
static void effect_main_region_Undefined_r1__choice_2_tr1(MqttClientStatemachine* handle);
static void effect_main_region_Undefined_r1__choice_2_tr0(MqttClientStatemachine* handle);
static void effect_main_region_Undefined_r1__choice_3_tr0(MqttClientStatemachine* handle);
static void effect_main_region_Undefined_r1__choice_4_tr0(MqttClientStatemachine* handle);
static void effect_main_region_Undefined_r1__choice_5_tr1(MqttClientStatemachine* handle);
static void effect_main_region_Undefined_r1__choice_5_tr0(MqttClientStatemachine* handle);
static void effect_main_region_Offline_r1__choice_0_tr0(MqttClientStatemachine* handle);
static void effect_main_region_Offline_r1__choice_1_tr0(MqttClientStatemachine* handle);
static void effect_main_region_Offline_r1__choice_2_tr0(MqttClientStatemachine* handle);
static void effect_main_region_Offline_r1__choice_3_tr0(MqttClientStatemachine* handle);
static void effect_main_region_Offline_r1__choice_4_tr0(MqttClientStatemachine* handle);
static void enact_main_region_Undefined_r1_Entry(MqttClientStatemachine* handle);
static void enact_main_region_Undefined_r1_ResetModule(MqttClientStatemachine* handle);
static void enact_main_region_Undefined_r1_TestModule(MqttClientStatemachine* handle);
static void enact_main_region_Undefined_r1_RestartModule(MqttClientStatemachine* handle);
static void enact_main_region_Online_r1_ConnectToBroker(MqttClientStatemachine* handle);
static void enact_main_region_Online_r1_PublishTopic(MqttClientStatemachine* handle);
static void enact_main_region_Online_r1_Wait(MqttClientStatemachine* handle);
static void enact_main_region_Offline_r1_SetTopic(MqttClientStatemachine* handle);
static void enact_main_region_Offline_r1_Entry(MqttClientStatemachine* handle);
static void enact_main_region_Offline_r1_SetStationMode(MqttClientStatemachine* handle);
static void enact_main_region_Offline_r1_ConfigureMqtt(MqttClientStatemachine* handle);
static void enact_main_region_Offline_r1_EnableDhcp(MqttClientStatemachine* handle);
static void enact_main_region_Offline_r1_ConnectToAccesspoint(MqttClientStatemachine* handle);
static void exact_main_region_Undefined_r1_Entry(MqttClientStatemachine* handle);
static void exact_main_region_Undefined_r1_ResetModule(MqttClientStatemachine* handle);
static void exact_main_region_Undefined_r1_TestModule(MqttClientStatemachine* handle);
static void exact_main_region_Undefined_r1_RestartModule(MqttClientStatemachine* handle);
static void exact_main_region_Online_r1_ConnectToBroker(MqttClientStatemachine* handle);
static void exact_main_region_Online_r1_PublishTopic(MqttClientStatemachine* handle);
static void exact_main_region_Online_r1_Wait(MqttClientStatemachine* handle);
static void exact_main_region_Offline_r1_SetTopic(MqttClientStatemachine* handle);
static void exact_main_region_Offline_r1_Entry(MqttClientStatemachine* handle);
static void exact_main_region_Offline_r1_SetStationMode(MqttClientStatemachine* handle);
static void exact_main_region_Offline_r1_ConfigureMqtt(MqttClientStatemachine* handle);
static void exact_main_region_Offline_r1_EnableDhcp(MqttClientStatemachine* handle);
static void exact_main_region_Offline_r1_ConnectToAccesspoint(MqttClientStatemachine* handle);
static void enseq_main_region_Undefined_default(MqttClientStatemachine* handle);
static void enseq_main_region_Undefined_r1_Entry_default(MqttClientStatemachine* handle);
static void enseq_main_region_Undefined_r1_ResetModule_default(MqttClientStatemachine* handle);
static void enseq_main_region_Undefined_r1_TestModule_default(MqttClientStatemachine* handle);
static void enseq_main_region_Undefined_r1_RestartModule_default(MqttClientStatemachine* handle);
static void enseq_main_region_Undefined_r1_ResetSystem_default(MqttClientStatemachine* handle);
static void enseq_main_region_Undefined_r1_Initialize_default(MqttClientStatemachine* handle);
static void enseq_main_region_Online_default(MqttClientStatemachine* handle);
static void enseq_main_region_Online_r1_ConnectToBroker_default(MqttClientStatemachine* handle);
static void enseq_main_region_Online_r1_Entry_default(MqttClientStatemachine* handle);
static void enseq_main_region_Online_r1_PublishTopic_default(MqttClientStatemachine* handle);
static void enseq_main_region_Online_r1_Wait_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_WifiConnectionLost(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_SetTopic_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_Entry_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_SetStationMode_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_ConfigureMqtt_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_EnableDhcp_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_ConnectToAccesspoint_default(MqttClientStatemachine* handle);
static void enseq_main_region_default(MqttClientStatemachine* handle);
static void enseq_main_region_Undefined_r1_default(MqttClientStatemachine* handle);
static void enseq_main_region_Online_r1_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_default(MqttClientStatemachine* handle);
static void enseq_main_region_Offline_r1_WifiConnectionLost(MqttClientStatemachine* handle);
static void exseq_main_region_Undefined(MqttClientStatemachine* handle);
static void exseq_main_region_Undefined_r1_Entry(MqttClientStatemachine* handle);
static void exseq_main_region_Undefined_r1_ResetModule(MqttClientStatemachine* handle);
static void exseq_main_region_Undefined_r1_TestModule(MqttClientStatemachine* handle);
static void exseq_main_region_Undefined_r1_RestartModule(MqttClientStatemachine* handle);
static void exseq_main_region_Undefined_r1_ResetSystem(MqttClientStatemachine* handle);
static void exseq_main_region_Undefined_r1_Initialize(MqttClientStatemachine* handle);
static void exseq_main_region_Online(MqttClientStatemachine* handle);
static void exseq_main_region_Online_r1_ConnectToBroker(MqttClientStatemachine* handle);
static void exseq_main_region_Online_r1_Entry(MqttClientStatemachine* handle);
static void exseq_main_region_Online_r1_PublishTopic(MqttClientStatemachine* handle);
static void exseq_main_region_Online_r1_Wait(MqttClientStatemachine* handle);
static void exseq_main_region_Offline(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1_SetTopic(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1_Entry(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1_SetStationMode(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1_ConfigureMqtt(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1_EnableDhcp(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1_ConnectToAccesspoint(MqttClientStatemachine* handle);
static void exseq_main_region(MqttClientStatemachine* handle);
static void exseq_main_region_Undefined_r1(MqttClientStatemachine* handle);
static void exseq_main_region_Online_r1(MqttClientStatemachine* handle);
static void exseq_main_region_Offline_r1(MqttClientStatemachine* handle);
static void react_main_region_Undefined_r1__choice_0(MqttClientStatemachine* handle);
static void react_main_region_Undefined_r1__choice_1(MqttClientStatemachine* handle);
static void react_main_region_Undefined_r1__choice_2(MqttClientStatemachine* handle);
static void react_main_region_Undefined_r1__choice_3(MqttClientStatemachine* handle);
static void react_main_region_Undefined_r1__choice_4(MqttClientStatemachine* handle);
static void react_main_region_Undefined_r1__choice_5(MqttClientStatemachine* handle);
static void react_main_region_Offline_r1__choice_0(MqttClientStatemachine* handle);
static void react_main_region_Offline_r1__choice_1(MqttClientStatemachine* handle);
static void react_main_region_Offline_r1__choice_2(MqttClientStatemachine* handle);
static void react_main_region_Offline_r1__choice_3(MqttClientStatemachine* handle);
static void react_main_region_Offline_r1__choice_4(MqttClientStatemachine* handle);
static void react_main_region__entry_Default(MqttClientStatemachine* handle);
static void react_main_region_Undefined_r1__entry_Default(MqttClientStatemachine* handle);
static void react_main_region_Online_r1__entry_Default(MqttClientStatemachine* handle);
static void react_main_region_Offline_r1__entry_Default(MqttClientStatemachine* handle);
static void react_main_region_Offline_r1_WifiConnectionLost(MqttClientStatemachine* handle);
static void react_main_region_Undefined_r1_ModuleReady(MqttClientStatemachine* handle);
static void react_main_region_Online_r1_ResetModule(MqttClientStatemachine* handle);
static void react_main_region_Offline_r1_WifiConnectionEstablished(MqttClientStatemachine* handle);
static void react_main_region_Offline_r1_ResetModule(MqttClientStatemachine* handle);

/*! State machine reactions. */
static sc_integer react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Undefined. */
static sc_integer main_region_Undefined_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Entry. */
static sc_integer main_region_Undefined_r1_Entry_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state ResetModule. */
static sc_integer main_region_Undefined_r1_ResetModule_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state TestModule. */
static sc_integer main_region_Undefined_r1_TestModule_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state RestartModule. */
static sc_integer main_region_Undefined_r1_RestartModule_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state ResetSystem. */
static sc_integer main_region_Undefined_r1_ResetSystem_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Initialize. */
static sc_integer main_region_Undefined_r1_Initialize_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);
/*! The reactions of state Online. */
static sc_integer main_region_Online_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state ConnectToBroker. */
static sc_integer main_region_Online_r1_ConnectToBroker_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Entry. */
static sc_integer main_region_Online_r1_Entry_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state PublishTopic. */
static sc_integer main_region_Online_r1_PublishTopic_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Wait. */
static sc_integer main_region_Online_r1_Wait_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Offline. */
static sc_integer main_region_Offline_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state SetTopic. */
static sc_integer main_region_Offline_r1_SetTopic_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Entry. */
static sc_integer main_region_Offline_r1_Entry_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state SetStationMode. */
static sc_integer main_region_Offline_r1_SetStationMode_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state ConfigureMqtt. */
static sc_integer main_region_Offline_r1_ConfigureMqtt_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state EnableDhcp. */
static sc_integer main_region_Offline_r1_EnableDhcp_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);

/*! The reactions of state ConnectToAccesspoint. */
static sc_integer main_region_Offline_r1_ConnectToAccesspoint_react(MqttClientStatemachine* handle, const sc_integer transitioned_before);


static void clear_out_events(MqttClientStatemachine* handle);

static void swap_in_events(MqttClientStatemachine* handle);

static void clear_in_events(MqttClientStatemachine* handle);

static void micro_step(MqttClientStatemachine* handle);





void mqttClientStatemachine_init(MqttClientStatemachine* handle)
{
	sc_integer i;
	
	for (i = 0; i < MQTTCLIENTSTATEMACHINE_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = MqttClientStatemachine_last_state;
	}
	
				
	clear_in_events(handle);
	swap_in_events(handle);
	clear_out_events(handle);
	
	sc_observable_init(&handle->ifaceSystem.reset);
	sc_observable_init(&handle->ifaceWizFi360.setStationMode);
	sc_observable_init(&handle->ifaceWizFi360.enableDhcp);
	sc_observable_init(&handle->ifaceWizFi360.connectToAccessPoint);
	sc_observable_init(&handle->ifaceWizFi360.configureMqtt);
	sc_observable_init(&handle->ifaceWizFi360.setTopic);
	sc_observable_init(&handle->ifaceWizFi360.connectToBroker);
	sc_observable_init(&handle->ifaceWizFi360.publishTopic);
	sc_observable_init(&handle->ifaceWizFi360.testModule);
	sc_observable_init(&handle->ifaceWizFi360.restartModule);
	sc_observable_init(&handle->ifaceWizFi360.initializeModule);
	sc_observable_init(&handle->ifaceWizFi360.resetModule);
	
	/* Default init sequence for statechart MqttClientStatemachine */
	handle->iface.dT = 200;
	handle->iface.publishInterval = 1000;
	handle->iface.watchdogTimer = 0;
	handle->ifaceWizFi360.wifiConnected = bool_false;
	handle->ifaceWizFi360.wifiFailCounter = 0;
	handle->ifaceWizFi360.testFailCounter = 0;
	handle->ifaceWizFi360.restartFailCounter = 0;
	handle->ifaceWizFi360.resetFailCounter = 0;
	
	handle->isExecuting = bool_false;
}

void mqttClientStatemachine_run_cycle(MqttClientStatemachine* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	clear_out_events(handle);
	swap_in_events(handle);
	micro_step(handle);
	handle->isExecuting = bool_false;
}

void mqttClientStatemachine_enter(MqttClientStatemachine* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart MqttClientStatemachine */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void mqttClientStatemachine_exit(MqttClientStatemachine* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart MqttClientStatemachine */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}


sc_boolean mqttClientStatemachine_is_active(const MqttClientStatemachine* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < MQTTCLIENTSTATEMACHINE_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != MqttClientStatemachine_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean mqttClientStatemachine_is_final(const MqttClientStatemachine* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

void mqttClientStatemachine_raise_time_event(MqttClientStatemachine* handle, sc_eventid evid)
{
	if ( ((sc_intptr_t)evid) >= ((sc_intptr_t)&(handle->timeEvents))
		&&  ((sc_intptr_t)evid) < ((sc_intptr_t)&(handle->timeEvents)) + (unsigned)sizeof(MqttClientStatemachineTimeEvents))
		{
		*(sc_boolean*)evid = bool_true;
	}
}

sc_boolean mqttClientStatemachine_is_state_active(const MqttClientStatemachine* handle, MqttClientStatemachineStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case MqttClientStatemachine_main_region_Undefined :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_UNDEFINED] >= MqttClientStatemachine_main_region_Undefined
				&& handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_UNDEFINED] <= MqttClientStatemachine_main_region_Undefined_r1_Initialize);
			break;
		case MqttClientStatemachine_main_region_Undefined_r1_Entry :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_UNDEFINED_R1_ENTRY] == MqttClientStatemachine_main_region_Undefined_r1_Entry
			);
			break;
		case MqttClientStatemachine_main_region_Undefined_r1_ResetModule :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_UNDEFINED_R1_RESETMODULE] == MqttClientStatemachine_main_region_Undefined_r1_ResetModule
			);
			break;
		case MqttClientStatemachine_main_region_Undefined_r1_TestModule :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_UNDEFINED_R1_TESTMODULE] == MqttClientStatemachine_main_region_Undefined_r1_TestModule
			);
			break;
		case MqttClientStatemachine_main_region_Undefined_r1_RestartModule :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_UNDEFINED_R1_RESTARTMODULE] == MqttClientStatemachine_main_region_Undefined_r1_RestartModule
			);
			break;
		case MqttClientStatemachine_main_region_Undefined_r1_ResetSystem :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_UNDEFINED_R1_RESETSYSTEM] == MqttClientStatemachine_main_region_Undefined_r1_ResetSystem
			);
			break;
		case MqttClientStatemachine_main_region_Undefined_r1_Initialize :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_UNDEFINED_R1_INITIALIZE] == MqttClientStatemachine_main_region_Undefined_r1_Initialize
			);
			break;
		case MqttClientStatemachine_main_region_Online :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE] >= MqttClientStatemachine_main_region_Online
				&& handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE] <= MqttClientStatemachine_main_region_Online_r1_Wait);
			break;
		case MqttClientStatemachine_main_region_Online_r1_ConnectToBroker :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE_R1_CONNECTTOBROKER] == MqttClientStatemachine_main_region_Online_r1_ConnectToBroker
			);
			break;
		case MqttClientStatemachine_main_region_Online_r1_Entry :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE_R1_ENTRY] == MqttClientStatemachine_main_region_Online_r1_Entry
			);
			break;
		case MqttClientStatemachine_main_region_Online_r1_PublishTopic :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE_R1_PUBLISHTOPIC] == MqttClientStatemachine_main_region_Online_r1_PublishTopic
			);
			break;
		case MqttClientStatemachine_main_region_Online_r1_Wait :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_ONLINE_R1_WAIT] == MqttClientStatemachine_main_region_Online_r1_Wait
			);
			break;
		case MqttClientStatemachine_main_region_Offline :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE] >= MqttClientStatemachine_main_region_Offline
				&& handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE] <= MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint);
			break;
		case MqttClientStatemachine_main_region_Offline_r1_SetTopic :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE_R1_SETTOPIC] == MqttClientStatemachine_main_region_Offline_r1_SetTopic
			);
			break;
		case MqttClientStatemachine_main_region_Offline_r1_Entry :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE_R1_ENTRY] == MqttClientStatemachine_main_region_Offline_r1_Entry
			);
			break;
		case MqttClientStatemachine_main_region_Offline_r1_SetStationMode :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE_R1_SETSTATIONMODE] == MqttClientStatemachine_main_region_Offline_r1_SetStationMode
			);
			break;
		case MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE_R1_CONFIGUREMQTT] == MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt
			);
			break;
		case MqttClientStatemachine_main_region_Offline_r1_EnableDhcp :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE_R1_ENABLEDHCP] == MqttClientStatemachine_main_region_Offline_r1_EnableDhcp
			);
			break;
		case MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTTCLIENTSTATEMACHINE_MAIN_REGION_OFFLINE_R1_CONNECTTOACCESSPOINT] == MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clear_out_events(MqttClientStatemachine* handle)
{
	handle->ifaceSystem.reset_raised = bool_false;
	handle->ifaceWizFi360.setStationMode_raised = bool_false;
	handle->ifaceWizFi360.enableDhcp_raised = bool_false;
	handle->ifaceWizFi360.connectToAccessPoint_raised = bool_false;
	handle->ifaceWizFi360.configureMqtt_raised = bool_false;
	handle->ifaceWizFi360.setTopic_raised = bool_false;
	handle->ifaceWizFi360.connectToBroker_raised = bool_false;
	handle->ifaceWizFi360.publishTopic_raised = bool_false;
	handle->ifaceWizFi360.testModule_raised = bool_false;
	handle->ifaceWizFi360.restartModule_raised = bool_false;
	handle->ifaceWizFi360.initializeModule_raised = bool_false;
	handle->ifaceWizFi360.resetModule_raised = bool_false;
}

static void swap_in_events(MqttClientStatemachine* handle)
{
	handle->current.ifaceWizFi360.ok_raised = handle->ifaceWizFi360.ok_raised;
	handle->ifaceWizFi360.ok_raised = bool_false;
	handle->current.ifaceWizFi360.error_raised = handle->ifaceWizFi360.error_raised;
	handle->ifaceWizFi360.error_raised = bool_false;
	handle->current.ifaceWizFi360.fail_raised = handle->ifaceWizFi360.fail_raised;
	handle->ifaceWizFi360.fail_raised = bool_false;
	handle->current.ifaceWizFi360.ready_raised = handle->ifaceWizFi360.ready_raised;
	handle->ifaceWizFi360.ready_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Undefined_r1_Entry_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_Entry_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_Entry_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Undefined_r1_ResetModule_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_ResetModule_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_ResetModule_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Undefined_r1_TestModule_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_TestModule_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_TestModule_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Undefined_r1_RestartModule_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_RestartModule_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_RestartModule_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Online_r1_ConnectToBroker_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_ConnectToBroker_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_ConnectToBroker_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Online_r1_PublishTopic_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_PublishTopic_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_PublishTopic_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Online_r1_Wait_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_Wait_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_Wait_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_SetTopic_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_SetTopic_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_SetTopic_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_Entry_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_Entry_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_Entry_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_SetStationMode_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_SetStationMode_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_SetStationMode_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_EnableDhcp_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_EnableDhcp_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_EnableDhcp_tev0_raised = bool_false;
	handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint_time_event_0_raised = handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint_tev0_raised;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint_tev0_raised = bool_false;
}

static void clear_in_events(MqttClientStatemachine* handle)
{
	handle->ifaceWizFi360.ok_raised = bool_false;
	handle->ifaceWizFi360.error_raised = bool_false;
	handle->ifaceWizFi360.fail_raised = bool_false;
	handle->ifaceWizFi360.ready_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_Entry_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_ResetModule_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_TestModule_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_RestartModule_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_ConnectToBroker_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_PublishTopic_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_Wait_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_SetTopic_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_Entry_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_SetStationMode_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_EnableDhcp_tev0_raised = bool_false;
	handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint_tev0_raised = bool_false;
}

static void micro_step(MqttClientStatemachine* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case MqttClientStatemachine_main_region_Undefined_r1_Entry :
		{
			main_region_Undefined_r1_Entry_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_ResetModule :
		{
			main_region_Undefined_r1_ResetModule_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_TestModule :
		{
			main_region_Undefined_r1_TestModule_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_RestartModule :
		{
			main_region_Undefined_r1_RestartModule_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_ResetSystem :
		{
			main_region_Undefined_r1_ResetSystem_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_Initialize :
		{
			main_region_Undefined_r1_Initialize_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_ConnectToBroker :
		{
			main_region_Online_r1_ConnectToBroker_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_Entry :
		{
			main_region_Online_r1_Entry_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_PublishTopic :
		{
			main_region_Online_r1_PublishTopic_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_Wait :
		{
			main_region_Online_r1_Wait_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_SetTopic :
		{
			main_region_Offline_r1_SetTopic_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_Entry :
		{
			main_region_Offline_r1_Entry_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_SetStationMode :
		{
			main_region_Offline_r1_SetStationMode_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt :
		{
			main_region_Offline_r1_ConfigureMqtt_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_EnableDhcp :
		{
			main_region_Offline_r1_EnableDhcp_react(handle, -1);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint :
		{
			main_region_Offline_r1_ConnectToAccesspoint_react(handle, -1);
			break;
		}
		default: break;
	}
}




sc_integer mqttClientStatemachine_get_dT(const MqttClientStatemachine* handle)
{
	return handle->iface.dT;
}
void mqttClientStatemachine_set_dT(MqttClientStatemachine* handle, sc_integer value)
{
	handle->iface.dT = value;
}
sc_integer mqttClientStatemachine_get_publishInterval(const MqttClientStatemachine* handle)
{
	return handle->iface.publishInterval;
}
void mqttClientStatemachine_set_publishInterval(MqttClientStatemachine* handle, sc_integer value)
{
	handle->iface.publishInterval = value;
}
sc_integer mqttClientStatemachine_get_watchdogTimer(const MqttClientStatemachine* handle)
{
	return handle->iface.watchdogTimer;
}
void mqttClientStatemachine_set_watchdogTimer(MqttClientStatemachine* handle, sc_integer value)
{
	handle->iface.watchdogTimer = value;
}

sc_observable* mqttClientStatemachine_System_get_reset(MqttClientStatemachine* handle)
{
	return &handle->ifaceSystem.reset;
}
sc_boolean mqttClientStatemachine_System_is_raised_reset(const MqttClientStatemachine* handle)
{
	return handle->ifaceSystem.reset_raised;
}

void mqttClientStatemachine_WizFi360_raise_ok(MqttClientStatemachine* handle)
{
	handle->ifaceWizFi360.ok_raised = bool_true;
}

void mqttClientStatemachine_WizFi360_raise_error(MqttClientStatemachine* handle)
{
	handle->ifaceWizFi360.error_raised = bool_true;
}

void mqttClientStatemachine_WizFi360_raise_fail(MqttClientStatemachine* handle)
{
	handle->ifaceWizFi360.fail_raised = bool_true;
}

void mqttClientStatemachine_WizFi360_raise_ready(MqttClientStatemachine* handle)
{
	handle->ifaceWizFi360.ready_raised = bool_true;
}


sc_observable* mqttClientStatemachine_WizFi360_get_setStationMode(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.setStationMode;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_setStationMode(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.setStationMode_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_enableDhcp(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.enableDhcp;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_enableDhcp(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.enableDhcp_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_connectToAccessPoint(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.connectToAccessPoint;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_connectToAccessPoint(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.connectToAccessPoint_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_configureMqtt(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.configureMqtt;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_configureMqtt(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.configureMqtt_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_setTopic(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.setTopic;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_setTopic(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.setTopic_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_connectToBroker(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.connectToBroker;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_connectToBroker(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.connectToBroker_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_publishTopic(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.publishTopic;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_publishTopic(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.publishTopic_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_testModule(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.testModule;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_testModule(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.testModule_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_restartModule(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.restartModule;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_restartModule(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.restartModule_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_initializeModule(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.initializeModule;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_initializeModule(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.initializeModule_raised;
}
sc_observable* mqttClientStatemachine_WizFi360_get_resetModule(MqttClientStatemachine* handle)
{
	return &handle->ifaceWizFi360.resetModule;
}
sc_boolean mqttClientStatemachine_WizFi360_is_raised_resetModule(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.resetModule_raised;
}

sc_boolean mqttClientStatemachine_WizFi360_get_wifiConnected(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.wifiConnected;
}
void mqttClientStatemachine_WizFi360_set_wifiConnected(MqttClientStatemachine* handle, sc_boolean value)
{
	handle->ifaceWizFi360.wifiConnected = value;
}
sc_integer mqttClientStatemachine_WizFi360_get_wifiFailCounter(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.wifiFailCounter;
}
void mqttClientStatemachine_WizFi360_set_wifiFailCounter(MqttClientStatemachine* handle, sc_integer value)
{
	handle->ifaceWizFi360.wifiFailCounter = value;
}
sc_integer mqttClientStatemachine_WizFi360_get_testFailCounter(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.testFailCounter;
}
void mqttClientStatemachine_WizFi360_set_testFailCounter(MqttClientStatemachine* handle, sc_integer value)
{
	handle->ifaceWizFi360.testFailCounter = value;
}
sc_integer mqttClientStatemachine_WizFi360_get_restartFailCounter(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.restartFailCounter;
}
void mqttClientStatemachine_WizFi360_set_restartFailCounter(MqttClientStatemachine* handle, sc_integer value)
{
	handle->ifaceWizFi360.restartFailCounter = value;
}
sc_integer mqttClientStatemachine_WizFi360_get_resetFailCounter(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.resetFailCounter;
}
void mqttClientStatemachine_WizFi360_set_resetFailCounter(MqttClientStatemachine* handle, sc_integer value)
{
	handle->ifaceWizFi360.resetFailCounter = value;
}

/* implementations of all internal functions */

static sc_boolean check_main_region_Undefined_r1__choice_0_tr1_tr1(MqttClientStatemachine* handle)
{
	return (handle->ifaceWizFi360.testFailCounter) > (10);
}

static sc_boolean check_main_region_Undefined_r1__choice_2_tr1_tr1(MqttClientStatemachine* handle)
{
	return (handle->ifaceWizFi360.restartFailCounter) > (4);
}

static sc_boolean check_main_region_Undefined_r1__choice_5_tr1_tr1(MqttClientStatemachine* handle)
{
	return (handle->ifaceWizFi360.resetFailCounter) > (4);
}
sc_integer mqttClientStatemachine_WizFi360_get_testFailCounter(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.testFailCounter;
}
void mqttClientStatemachine_WizFi360_set_testFailCounter(MqttClientStatemachine* handle, sc_integer value)
{
	handle->ifaceWizFi360.testFailCounter = value;
}
sc_integer mqttClientStatemachine_WizFi360_get_restartFailCounter(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.restartFailCounter;
}
void mqttClientStatemachine_WizFi360_set_restartFailCounter(MqttClientStatemachine* handle, sc_integer value)
{
	handle->ifaceWizFi360.restartFailCounter = value;
}
sc_integer mqttClientStatemachine_WizFi360_get_resetFailCounter(const MqttClientStatemachine* handle)
{
	return handle->ifaceWizFi360.resetFailCounter;
}
void mqttClientStatemachine_WizFi360_set_resetFailCounter(MqttClientStatemachine* handle, sc_integer value)
{
	handle->ifaceWizFi360.resetFailCounter = value;
}

static void effect_main_region_Undefined_tr0(MqttClientStatemachine* handle)
{
	exseq_main_region_Undefined(handle);
	enseq_main_region_Offline_default(handle);
	react(handle, 0);
}

static void effect_main_region_Online_tr1(MqttClientStatemachine* handle)
{
	exseq_main_region_Online(handle);
	enseq_main_region_Undefined_default(handle);
	react(handle, 0);
}

static void effect_main_region_Offline_tr0(MqttClientStatemachine* handle)
{
	exseq_main_region_Offline(handle);
	enseq_main_region_Online_default(handle);
	react(handle, 0);
}

static void effect_main_region_Offline_tr1(MqttClientStatemachine* handle)
{
	exseq_main_region_Offline(handle);
	enseq_main_region_Undefined_default(handle);
	react(handle, 0);
}

static void effect_main_region_Undefined_r1__choice_0_tr1(MqttClientStatemachine* handle)
{
	react_main_region_Undefined_r1__choice_3(handle);
}

static void effect_main_region_Undefined_r1__choice_0_tr0(MqttClientStatemachine* handle)
{
	react_main_region_Undefined_r1__choice_1(handle);
}

static void effect_main_region_Undefined_r1__choice_1_tr0(MqttClientStatemachine* handle)
{
	sc_observable_next(&handle->ifaceWizFi360.initializeModule);
	handle->ifaceWizFi360.initializeModule_raised = bool_true;
	enseq_main_region_Undefined_r1_Initialize_default(handle);
}

static void effect_main_region_Undefined_r1__choice_2_tr1(MqttClientStatemachine* handle)
{
	react_main_region_Undefined_r1__choice_3(handle);
}

static void effect_main_region_Undefined_r1__choice_2_tr0(MqttClientStatemachine* handle)
{
	react_main_region_Undefined_r1__choice_0(handle);
}

static void effect_main_region_Undefined_r1__choice_3_tr0(MqttClientStatemachine* handle)
{
	react_main_region_Undefined_r1__choice_4(handle);
}

static void effect_main_region_Undefined_r1__choice_4_tr0(MqttClientStatemachine* handle)
{
	sc_observable_next(&handle->ifaceWizFi360.resetModule);
	handle->ifaceWizFi360.resetModule_raised = bool_true;
	enseq_main_region_Undefined_r1_ResetModule_default(handle);
}

static void effect_main_region_Undefined_r1__choice_5_tr1(MqttClientStatemachine* handle)
{
	sc_observable_next(&handle->ifaceSystem.reset);
	handle->ifaceSystem.reset_raised = bool_true;
	enseq_main_region_Undefined_r1_ResetSystem_default(handle);
}

static void effect_main_region_Undefined_r1__choice_5_tr0(MqttClientStatemachine* handle)
{
	react_main_region_Undefined_r1__choice_4(handle);
}

static void effect_main_region_Offline_r1__choice_0_tr0(MqttClientStatemachine* handle)
{
	react_main_region_Offline_r1__choice_1(handle);
}

static void effect_main_region_Offline_r1__choice_1_tr0(MqttClientStatemachine* handle)
{
	react_main_region_Offline_r1__choice_2(handle);
}

static void effect_main_region_Offline_r1__choice_2_tr0(MqttClientStatemachine* handle)
{
	react_main_region_Offline_r1__choice_3(handle);
}

static void effect_main_region_Offline_r1__choice_3_tr0(MqttClientStatemachine* handle)
{
	react_main_region_Offline_r1_ResetModule(handle);
}

static void effect_main_region_Offline_r1__choice_4_tr0(MqttClientStatemachine* handle)
{
	react_main_region_Offline_r1_ResetModule(handle);
}

/* Entry action for state 'Entry'. */
static void enact_main_region_Undefined_r1_Entry(MqttClientStatemachine* handle)
{
	/* Entry action for state 'Entry'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_Entry_tev0_raised) , (1 * 1000), bool_false);
}

/* Entry action for state 'ResetModule'. */
static void enact_main_region_Undefined_r1_ResetModule(MqttClientStatemachine* handle)
{
	/* Entry action for state 'ResetModule'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_ResetModule_tev0_raised) , (4 * 1000), bool_false);
}

/* Entry action for state 'TestModule'. */
static void enact_main_region_Undefined_r1_TestModule(MqttClientStatemachine* handle)
{
	/* Entry action for state 'TestModule'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_TestModule_tev0_raised) , (1 * 1000), bool_false);
}

/* Entry action for state 'RestartModule'. */
static void enact_main_region_Undefined_r1_RestartModule(MqttClientStatemachine* handle)
{
	/* Entry action for state 'RestartModule'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_RestartModule_tev0_raised) , (3 * 1000), bool_false);
}

/* Entry action for state 'ConnectToBroker'. */
static void enact_main_region_Online_r1_ConnectToBroker(MqttClientStatemachine* handle)
{
	/* Entry action for state 'ConnectToBroker'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_ConnectToBroker_tev0_raised) , (10 * 1000), bool_false);
}

/* Entry action for state 'PublishTopic'. */
static void enact_main_region_Online_r1_PublishTopic(MqttClientStatemachine* handle)
{
	/* Entry action for state 'PublishTopic'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_PublishTopic_tev0_raised) , (5 * 1000), bool_false);
}

/* Entry action for state 'Wait'. */
static void enact_main_region_Online_r1_Wait(MqttClientStatemachine* handle)
{
	/* Entry action for state 'Wait'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_Wait_tev0_raised) , ((handle->iface.publishInterval - (2 * handle->iface.dT))), bool_false);
}

/* Entry action for state 'SetTopic'. */
static void enact_main_region_Offline_r1_SetTopic(MqttClientStatemachine* handle)
{
	/* Entry action for state 'SetTopic'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_SetTopic_tev0_raised) , (2 * 1000), bool_false);
}

/* Entry action for state 'Entry'. */
static void enact_main_region_Offline_r1_Entry(MqttClientStatemachine* handle)
{
	/* Entry action for state 'Entry'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_Entry_tev0_raised) , (1 * 1000), bool_false);
}

/* Entry action for state 'SetStationMode'. */
static void enact_main_region_Offline_r1_SetStationMode(MqttClientStatemachine* handle)
{
	/* Entry action for state 'SetStationMode'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_SetStationMode_tev0_raised) , (2 * 1000), bool_false);
}

/* Entry action for state 'ConfigureMqtt'. */
static void enact_main_region_Offline_r1_ConfigureMqtt(MqttClientStatemachine* handle)
{
	/* Entry action for state 'ConfigureMqtt'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt_tev0_raised) , (2 * 1000), bool_false);
}

/* Entry action for state 'EnableDhcp'. */
static void enact_main_region_Offline_r1_EnableDhcp(MqttClientStatemachine* handle)
{
	/* Entry action for state 'EnableDhcp'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_EnableDhcp_tev0_raised) , (2 * 1000), bool_false);
}

/* Entry action for state 'ConnectToAccesspoint'. */
static void enact_main_region_Offline_r1_ConnectToAccesspoint(MqttClientStatemachine* handle)
{
	/* Entry action for state 'ConnectToAccesspoint'. */
	mqttClientStatemachine_set_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint_tev0_raised) , (30 * 1000), bool_false);
}

/* Exit action for state 'Entry'. */
static void exact_main_region_Undefined_r1_Entry(MqttClientStatemachine* handle)
{
	/* Exit action for state 'Entry'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_Entry_tev0_raised) );		
}

/* Exit action for state 'ResetModule'. */
static void exact_main_region_Undefined_r1_ResetModule(MqttClientStatemachine* handle)
{
	/* Exit action for state 'ResetModule'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_ResetModule_tev0_raised) );		
}

/* Exit action for state 'TestModule'. */
static void exact_main_region_Undefined_r1_TestModule(MqttClientStatemachine* handle)
{
	/* Exit action for state 'TestModule'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_TestModule_tev0_raised) );		
}

/* Exit action for state 'RestartModule'. */
static void exact_main_region_Undefined_r1_RestartModule(MqttClientStatemachine* handle)
{
	/* Exit action for state 'RestartModule'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Undefined_r1_RestartModule_tev0_raised) );		
}

/* Exit action for state 'ConnectToBroker'. */
static void exact_main_region_Online_r1_ConnectToBroker(MqttClientStatemachine* handle)
{
	/* Exit action for state 'ConnectToBroker'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_ConnectToBroker_tev0_raised) );		
}

/* Exit action for state 'PublishTopic'. */
static void exact_main_region_Online_r1_PublishTopic(MqttClientStatemachine* handle)
{
	/* Exit action for state 'PublishTopic'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_PublishTopic_tev0_raised) );		
}

/* Exit action for state 'Wait'. */
static void exact_main_region_Online_r1_Wait(MqttClientStatemachine* handle)
{
	/* Exit action for state 'Wait'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Online_r1_Wait_tev0_raised) );		
}

/* Exit action for state 'SetTopic'. */
static void exact_main_region_Offline_r1_SetTopic(MqttClientStatemachine* handle)
{
	/* Exit action for state 'SetTopic'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_SetTopic_tev0_raised) );		
}

/* Exit action for state 'Entry'. */
static void exact_main_region_Offline_r1_Entry(MqttClientStatemachine* handle)
{
	/* Exit action for state 'Entry'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_Entry_tev0_raised) );		
}

/* Exit action for state 'SetStationMode'. */
static void exact_main_region_Offline_r1_SetStationMode(MqttClientStatemachine* handle)
{
	/* Exit action for state 'SetStationMode'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_SetStationMode_tev0_raised) );		
}

/* Exit action for state 'ConfigureMqtt'. */
static void exact_main_region_Offline_r1_ConfigureMqtt(MqttClientStatemachine* handle)
{
	/* Exit action for state 'ConfigureMqtt'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt_tev0_raised) );		
}

/* Exit action for state 'EnableDhcp'. */
static void exact_main_region_Offline_r1_EnableDhcp(MqttClientStatemachine* handle)
{
	/* Exit action for state 'EnableDhcp'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_EnableDhcp_tev0_raised) );		
}

/* Exit action for state 'ConnectToAccesspoint'. */
static void exact_main_region_Offline_r1_ConnectToAccesspoint(MqttClientStatemachine* handle)
{
	/* Exit action for state 'ConnectToAccesspoint'. */
	mqttClientStatemachine_unset_timer(handle, (sc_eventid) &(handle->timeEvents.mqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint_tev0_raised) );		
}

/* 'default' enter sequence for state Undefined */
static void enseq_main_region_Undefined_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Undefined */
	enseq_main_region_Undefined_r1_default(handle);
}

/* 'default' enter sequence for state Entry */
static void enseq_main_region_Undefined_r1_Entry_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Entry */
	enact_main_region_Undefined_r1_Entry(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Undefined_r1_Entry;
}

/* 'default' enter sequence for state ResetModule */
static void enseq_main_region_Undefined_r1_ResetModule_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state ResetModule */
	enact_main_region_Undefined_r1_ResetModule(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Undefined_r1_ResetModule;
}

/* 'default' enter sequence for state TestModule */
static void enseq_main_region_Undefined_r1_TestModule_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state TestModule */
	enact_main_region_Undefined_r1_TestModule(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Undefined_r1_TestModule;
}

/* 'default' enter sequence for state RestartModule */
static void enseq_main_region_Undefined_r1_RestartModule_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state RestartModule */
	enact_main_region_Undefined_r1_RestartModule(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Undefined_r1_RestartModule;
}

/* 'default' enter sequence for state ResetSystem */
static void enseq_main_region_Undefined_r1_ResetSystem_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state ResetSystem */
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Undefined_r1_ResetSystem;
}

/* 'default' enter sequence for state Initialize */
static void enseq_main_region_Undefined_r1_Initialize_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Initialize */
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Undefined_r1_Initialize;
}

/* 'default' enter sequence for state Online */
static void enseq_main_region_Online_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Online */
	enseq_main_region_Online_r1_default(handle);
}

/* 'default' enter sequence for state ConnectToBroker */
static void enseq_main_region_Online_r1_ConnectToBroker_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state ConnectToBroker */
	enact_main_region_Online_r1_ConnectToBroker(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Online_r1_ConnectToBroker;
}

/* 'default' enter sequence for state Entry */
static void enseq_main_region_Online_r1_Entry_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Entry */
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Online_r1_Entry;
}

/* 'default' enter sequence for state PublishTopic */
static void enseq_main_region_Online_r1_PublishTopic_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state PublishTopic */
	enact_main_region_Online_r1_PublishTopic(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Online_r1_PublishTopic;
}

/* 'default' enter sequence for state Wait */
static void enseq_main_region_Online_r1_Wait_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Wait */
	enact_main_region_Online_r1_Wait(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Online_r1_Wait;
}

/* 'WifiConnectionLost' enter sequence for state Offline */
static void enseq_main_region_Offline_WifiConnectionLost(MqttClientStatemachine* handle)
{
	/* 'WifiConnectionLost' enter sequence for state Offline */
	enseq_main_region_Offline_r1_WifiConnectionLost(handle);
}

/* 'default' enter sequence for state Offline */
static void enseq_main_region_Offline_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Offline */
	enseq_main_region_Offline_r1_default(handle);
}

/* 'default' enter sequence for state SetTopic */
static void enseq_main_region_Offline_r1_SetTopic_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state SetTopic */
	enact_main_region_Offline_r1_SetTopic(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Offline_r1_SetTopic;
}

/* 'default' enter sequence for state Entry */
static void enseq_main_region_Offline_r1_Entry_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state Entry */
	enact_main_region_Offline_r1_Entry(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Offline_r1_Entry;
}

/* 'default' enter sequence for state SetStationMode */
static void enseq_main_region_Offline_r1_SetStationMode_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state SetStationMode */
	enact_main_region_Offline_r1_SetStationMode(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Offline_r1_SetStationMode;
}

/* 'default' enter sequence for state ConfigureMqtt */
static void enseq_main_region_Offline_r1_ConfigureMqtt_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state ConfigureMqtt */
	enact_main_region_Offline_r1_ConfigureMqtt(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt;
}

/* 'default' enter sequence for state EnableDhcp */
static void enseq_main_region_Offline_r1_EnableDhcp_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state EnableDhcp */
	enact_main_region_Offline_r1_EnableDhcp(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Offline_r1_EnableDhcp;
}

/* 'default' enter sequence for state ConnectToAccesspoint */
static void enseq_main_region_Offline_r1_ConnectToAccesspoint_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for state ConnectToAccesspoint */
	enact_main_region_Offline_r1_ConnectToAccesspoint(handle);
	handle->stateConfVector[0] = MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_Undefined_r1_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_Undefined_r1__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_Online_r1_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_Online_r1__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_Offline_r1_default(MqttClientStatemachine* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_Offline_r1__entry_Default(handle);
}

/* 'WifiConnectionLost' enter sequence for region r1 */
static void enseq_main_region_Offline_r1_WifiConnectionLost(MqttClientStatemachine* handle)
{
	/* 'WifiConnectionLost' enter sequence for region r1 */
	react_main_region_Offline_r1_WifiConnectionLost(handle);
}

/* Default exit sequence for state Undefined */
static void exseq_main_region_Undefined(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Undefined */
	exseq_main_region_Undefined_r1(handle);
}

/* Default exit sequence for state Entry */
static void exseq_main_region_Undefined_r1_Entry(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Entry */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Undefined_r1_Entry(handle);
}

/* Default exit sequence for state ResetModule */
static void exseq_main_region_Undefined_r1_ResetModule(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state ResetModule */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Undefined_r1_ResetModule(handle);
}

/* Default exit sequence for state TestModule */
static void exseq_main_region_Undefined_r1_TestModule(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state TestModule */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Undefined_r1_TestModule(handle);
}

/* Default exit sequence for state RestartModule */
static void exseq_main_region_Undefined_r1_RestartModule(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state RestartModule */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Undefined_r1_RestartModule(handle);
}

/* Default exit sequence for state ResetSystem */
static void exseq_main_region_Undefined_r1_ResetSystem(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state ResetSystem */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
}

/* Default exit sequence for state Initialize */
static void exseq_main_region_Undefined_r1_Initialize(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Initialize */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
}
/* Default exit sequence for state Online */
static void exseq_main_region_Online(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Online */
	exseq_main_region_Online_r1(handle);
}

/* Default exit sequence for state ConnectToBroker */
static void exseq_main_region_Online_r1_ConnectToBroker(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state ConnectToBroker */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Online_r1_ConnectToBroker(handle);
}

/* Default exit sequence for state Entry */
static void exseq_main_region_Online_r1_Entry(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Entry */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
}

/* Default exit sequence for state PublishTopic */
static void exseq_main_region_Online_r1_PublishTopic(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state PublishTopic */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Online_r1_PublishTopic(handle);
}

/* Default exit sequence for state Wait */
static void exseq_main_region_Online_r1_Wait(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Wait */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Online_r1_Wait(handle);
}

/* Default exit sequence for state Offline */
static void exseq_main_region_Offline(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Offline */
	exseq_main_region_Offline_r1(handle);
}

/* Default exit sequence for state SetTopic */
static void exseq_main_region_Offline_r1_SetTopic(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state SetTopic */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Offline_r1_SetTopic(handle);
}

/* Default exit sequence for state Entry */
static void exseq_main_region_Offline_r1_Entry(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state Entry */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Offline_r1_Entry(handle);
}

/* Default exit sequence for state SetStationMode */
static void exseq_main_region_Offline_r1_SetStationMode(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state SetStationMode */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Offline_r1_SetStationMode(handle);
}

/* Default exit sequence for state ConfigureMqtt */
static void exseq_main_region_Offline_r1_ConfigureMqtt(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state ConfigureMqtt */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Offline_r1_ConfigureMqtt(handle);
}

/* Default exit sequence for state EnableDhcp */
static void exseq_main_region_Offline_r1_EnableDhcp(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state EnableDhcp */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Offline_r1_EnableDhcp(handle);
}

/* Default exit sequence for state ConnectToAccesspoint */
static void exseq_main_region_Offline_r1_ConnectToAccesspoint(MqttClientStatemachine* handle)
{
	/* Default exit sequence for state ConnectToAccesspoint */
	handle->stateConfVector[0] = MqttClientStatemachine_last_state;
	exact_main_region_Offline_r1_ConnectToAccesspoint(handle);
}

/* Default exit sequence for region main region */
static void exseq_main_region(MqttClientStatemachine* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of MqttClientStatemachine.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case MqttClientStatemachine_main_region_Undefined_r1_Entry :
		{
			exseq_main_region_Undefined_r1_Entry(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_ResetModule :
		{
			exseq_main_region_Undefined_r1_ResetModule(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_TestModule :
		{
			exseq_main_region_Undefined_r1_TestModule(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_RestartModule :
		{
			exseq_main_region_Undefined_r1_RestartModule(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_ResetSystem :
		{
			exseq_main_region_Undefined_r1_ResetSystem(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_Initialize :
		{
			exseq_main_region_Undefined_r1_Initialize(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_ConnectToBroker :
		{
			exseq_main_region_Online_r1_ConnectToBroker(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_Entry :
		{
			exseq_main_region_Online_r1_Entry(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_PublishTopic :
		{
			exseq_main_region_Online_r1_PublishTopic(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_Wait :
		{
			exseq_main_region_Online_r1_Wait(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_SetTopic :
		{
			exseq_main_region_Offline_r1_SetTopic(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_Entry :
		{
			exseq_main_region_Offline_r1_Entry(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_SetStationMode :
		{
			exseq_main_region_Offline_r1_SetStationMode(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt :
		{
			exseq_main_region_Offline_r1_ConfigureMqtt(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_EnableDhcp :
		{
			exseq_main_region_Offline_r1_EnableDhcp(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint :
		{
			exseq_main_region_Offline_r1_ConnectToAccesspoint(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_main_region_Undefined_r1(MqttClientStatemachine* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of MqttClientStatemachine.main_region.Undefined.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case MqttClientStatemachine_main_region_Undefined_r1_Entry :
		{
			exseq_main_region_Undefined_r1_Entry(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_ResetModule :
		{
			exseq_main_region_Undefined_r1_ResetModule(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_TestModule :
		{
			exseq_main_region_Undefined_r1_TestModule(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_RestartModule :
		{
			exseq_main_region_Undefined_r1_RestartModule(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_ResetSystem :
		{
			exseq_main_region_Undefined_r1_ResetSystem(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Undefined_r1_Initialize :
		{
			exseq_main_region_Undefined_r1_Initialize(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_main_region_Online_r1(MqttClientStatemachine* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of MqttClientStatemachine.main_region.Online.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case MqttClientStatemachine_main_region_Online_r1_ConnectToBroker :
		{
			exseq_main_region_Online_r1_ConnectToBroker(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_Entry :
		{
			exseq_main_region_Online_r1_Entry(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_PublishTopic :
		{
			exseq_main_region_Online_r1_PublishTopic(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Online_r1_Wait :
		{
			exseq_main_region_Online_r1_Wait(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_main_region_Offline_r1(MqttClientStatemachine* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of MqttClientStatemachine.main_region.Offline.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case MqttClientStatemachine_main_region_Offline_r1_SetTopic :
		{
			exseq_main_region_Offline_r1_SetTopic(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_Entry :
		{
			exseq_main_region_Offline_r1_Entry(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_SetStationMode :
		{
			exseq_main_region_Offline_r1_SetStationMode(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt :
		{
			exseq_main_region_Offline_r1_ConfigureMqtt(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_EnableDhcp :
		{
			exseq_main_region_Offline_r1_EnableDhcp(handle);
			break;
		}
		case MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint :
		{
			exseq_main_region_Offline_r1_ConnectToAccesspoint(handle);
			break;
		}
		default: break;
	}
}

/* The reactions of state null. */
static void react_main_region_Undefined_r1__choice_0(MqttClientStatemachine* handle)
{
	/* The reactions of state null. */
	if (check_main_region_Undefined_r1__choice_0_tr1_tr1(handle) == bool_true)
	{ 
		effect_main_region_Undefined_r1__choice_0_tr1(handle);
	}  else
	{
		effect_main_region_Undefined_r1__choice_0_tr0(handle);
	}
}

/* The reactions of state null. */
static void react_main_region_Undefined_r1__choice_1(MqttClientStatemachine* handle)
{
	/* The reactions of state null. */
	effect_main_region_Undefined_r1__choice_1_tr0(handle);
}

/* The reactions of state null. */
static void react_main_region_Undefined_r1__choice_2(MqttClientStatemachine* handle)
{
	/* The reactions of state null. */
	if (check_main_region_Undefined_r1__choice_2_tr1_tr1(handle) == bool_true)
	{ 
		effect_main_region_Undefined_r1__choice_2_tr1(handle);
	}  else
	{
		effect_main_region_Undefined_r1__choice_2_tr0(handle);
	}
}

/* The reactions of state null. */
static void react_main_region_Undefined_r1__choice_3(MqttClientStatemachine* handle)
{
	/* The reactions of state null. */
	effect_main_region_Undefined_r1__choice_3_tr0(handle);
}

/* The reactions of state null. */
static void react_main_region_Undefined_r1__choice_4(MqttClientStatemachine* handle)
{
	/* The reactions of state null. */
	effect_main_region_Undefined_r1__choice_4_tr0(handle);
}

/* The reactions of state null. */
static void react_main_region_Undefined_r1__choice_5(MqttClientStatemachine* handle)
{
	/* The reactions of state null. */
	if (check_main_region_Undefined_r1__choice_5_tr1_tr1(handle) == bool_true)
	{ 
		effect_main_region_Undefined_r1__choice_5_tr1(handle);
	}  else
	{
		effect_main_region_Undefined_r1__choice_5_tr0(handle);
	}
}

/* The reactions of state null. */
static void react_main_region_Offline_r1__choice_0(MqttClientStatemachine* handle)
{
	/* The reactions of state null. */
	effect_main_region_Offline_r1__choice_0_tr0(handle);
}

/* The reactions of state null. */
static void react_main_region_Offline_r1__choice_1(MqttClientStatemachine* handle)
{
	/* The reactions of state null. */
	effect_main_region_Offline_r1__choice_1_tr0(handle);
}

/* The reactions of state null. */
static void react_main_region_Offline_r1__choice_2(MqttClientStatemachine* handle)
{
	/* The reactions of state null. */
	effect_main_region_Offline_r1__choice_2_tr0(handle);
}

/* The reactions of state null. */
static void react_main_region_Offline_r1__choice_3(MqttClientStatemachine* handle)
{
	/* The reactions of state null. */
	effect_main_region_Offline_r1__choice_3_tr0(handle);
}

/* The reactions of state null. */
static void react_main_region_Offline_r1__choice_4(MqttClientStatemachine* handle)
{
	/* The reactions of state null. */
	effect_main_region_Offline_r1__choice_4_tr0(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(MqttClientStatemachine* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Undefined_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_Undefined_r1__entry_Default(MqttClientStatemachine* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Undefined_r1_Entry_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_Online_r1__entry_Default(MqttClientStatemachine* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Online_r1_Entry_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_Offline_r1__entry_Default(MqttClientStatemachine* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Offline_r1_Entry_default(handle);
}

/* Default react sequence for initial entry WifiConnectionLost */
static void react_main_region_Offline_r1_WifiConnectionLost(MqttClientStatemachine* handle)
{
	/* Default react sequence for initial entry WifiConnectionLost */
	handle->ifaceWizFi360.wifiFailCounter = 0;
	enseq_main_region_Offline_r1_ConnectToAccesspoint_default(handle);
}

/* The reactions of exit ModuleReady. */
static void react_main_region_Undefined_r1_ModuleReady(MqttClientStatemachine* handle)
{
	/* The reactions of exit ModuleReady. */
	effect_main_region_Undefined_tr0(handle);
}

/* The reactions of exit ResetModule. */
static void react_main_region_Online_r1_ResetModule(MqttClientStatemachine* handle)
{
	/* The reactions of exit ResetModule. */
	effect_main_region_Online_tr1(handle);
}

/* The reactions of exit WifiConnectionEstablished. */
static void react_main_region_Offline_r1_WifiConnectionEstablished(MqttClientStatemachine* handle)
{
	/* The reactions of exit WifiConnectionEstablished. */
	effect_main_region_Offline_tr0(handle);
}

/* The reactions of exit ResetModule. */
static void react_main_region_Offline_r1_ResetModule(MqttClientStatemachine* handle)
{
	/* The reactions of exit ResetModule. */
	effect_main_region_Offline_tr1(handle);
}


static sc_integer react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer main_region_Undefined_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Undefined. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Undefined_r1_Entry_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Entry. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.timeEvents.MqttClientStatemachine_main_region_Undefined_r1_Entry_time_event_0_raised == bool_true)
		{ 
			exseq_main_region_Undefined_r1_Entry(handle);
			handle->ifaceWizFi360.testFailCounter = 0;
			handle->ifaceWizFi360.restartFailCounter = 0;
			handle->ifaceWizFi360.resetFailCounter = 0;
			react_main_region_Undefined_r1__choice_1(handle);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Undefined_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Undefined_r1_ResetModule_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ResetModule. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.timeEvents.MqttClientStatemachine_main_region_Undefined_r1_ResetModule_time_event_0_raised == bool_true)
		{ 
			exseq_main_region_Undefined_r1_ResetModule(handle);
			handle->ifaceWizFi360.resetFailCounter += 1;
			react_main_region_Undefined_r1__choice_5(handle);
			transitioned_after = 0;
		}  else
		{
			if (handle->current.ifaceWizFi360.ready_raised == bool_true)
			{ 
				exseq_main_region_Undefined_r1_ResetModule(handle);
				react_main_region_Undefined_r1_ModuleReady(handle);
				transitioned_after = 0;
			} 
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Undefined_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Undefined_r1_TestModule_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state TestModule. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Undefined_r1_TestModule(handle);
			sc_observable_next(&handle->ifaceWizFi360.restartModule);
			handle->ifaceWizFi360.restartModule_raised = bool_true;
			enseq_main_region_Undefined_r1_RestartModule_default(handle);
			main_region_Undefined_react(handle, 0);
			transitioned_after = 0;
		}  else
		{
			if (handle->current.timeEvents.MqttClientStatemachine_main_region_Undefined_r1_TestModule_time_event_0_raised == bool_true)
			{ 
				exseq_main_region_Undefined_r1_TestModule(handle);
				handle->ifaceWizFi360.testFailCounter += 1;
				react_main_region_Undefined_r1__choice_0(handle);
				transitioned_after = 0;
			} 
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Undefined_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Undefined_r1_RestartModule_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state RestartModule. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ready_raised == bool_true)
		{ 
			exseq_main_region_Undefined_r1_RestartModule(handle);
			react_main_region_Undefined_r1_ModuleReady(handle);
			transitioned_after = 0;
		}  else
		{
			if (handle->current.timeEvents.MqttClientStatemachine_main_region_Undefined_r1_RestartModule_time_event_0_raised == bool_true)
			{ 
				exseq_main_region_Undefined_r1_RestartModule(handle);
				handle->ifaceWizFi360.restartFailCounter += 1;
				react_main_region_Undefined_r1__choice_2(handle);
				transitioned_after = 0;
			} 
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Undefined_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Undefined_r1_ResetSystem_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ResetSystem. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Undefined_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Undefined_r1_Initialize_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Initialize. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		exseq_main_region_Undefined_r1_Initialize(handle);
		sc_observable_next(&handle->ifaceWizFi360.testModule);
		handle->ifaceWizFi360.testModule_raised = bool_true;
		enseq_main_region_Undefined_r1_TestModule_default(handle);
		main_region_Undefined_react(handle, 0);
		transitioned_after = 0;
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Undefined_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Online_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Online. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->ifaceWizFi360.wifiConnected == bool_false)
		{ 
			exseq_main_region_Online(handle);
			enseq_main_region_Offline_WifiConnectionLost(handle);
			react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Online_r1_ConnectToBroker_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ConnectToBroker. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Online_r1_ConnectToBroker(handle);
			sc_observable_next(&handle->ifaceWizFi360.publishTopic);
			handle->ifaceWizFi360.publishTopic_raised = bool_true;
			enseq_main_region_Online_r1_PublishTopic_default(handle);
			main_region_Online_react(handle, 0);
			transitioned_after = 0;
		}  else
		{
			if (handle->current.timeEvents.MqttClientStatemachine_main_region_Online_r1_ConnectToBroker_time_event_0_raised == bool_true)
			{ 
				exseq_main_region_Online_r1_ConnectToBroker(handle);
				react_main_region_Online_r1_ResetModule(handle);
				transitioned_after = 0;
			} 
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Online_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Online_r1_Entry_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Entry. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		exseq_main_region_Online_r1_Entry(handle);
		sc_observable_next(&handle->ifaceWizFi360.connectToBroker);
		handle->ifaceWizFi360.connectToBroker_raised = bool_true;
		enseq_main_region_Online_r1_ConnectToBroker_default(handle);
		main_region_Online_react(handle, 0);
		transitioned_after = 0;
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Online_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Online_r1_PublishTopic_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state PublishTopic. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Online_r1_PublishTopic(handle);
			enseq_main_region_Online_r1_Wait_default(handle);
			main_region_Online_react(handle, 0);
			transitioned_after = 0;
		}  else
		{
			if (handle->current.timeEvents.MqttClientStatemachine_main_region_Online_r1_PublishTopic_time_event_0_raised == bool_true)
			{ 
				exseq_main_region_Online_r1_PublishTopic(handle);
				react_main_region_Online_r1_ResetModule(handle);
				transitioned_after = 0;
			} 
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Online_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Online_r1_Wait_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Wait. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.timeEvents.MqttClientStatemachine_main_region_Online_r1_Wait_time_event_0_raised == bool_true)
		{ 
			exseq_main_region_Online_r1_Wait(handle);
			sc_observable_next(&handle->ifaceWizFi360.publishTopic);
			handle->ifaceWizFi360.publishTopic_raised = bool_true;
			enseq_main_region_Online_r1_PublishTopic_default(handle);
			main_region_Online_react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Online_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Offline. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_r1_SetTopic_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state SetTopic. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Offline_r1_SetTopic(handle);
			sc_observable_next(&handle->ifaceWizFi360.connectToAccessPoint);
			handle->ifaceWizFi360.connectToAccessPoint_raised = bool_true;
			handle->ifaceWizFi360.wifiFailCounter = 0;
			enseq_main_region_Offline_r1_ConnectToAccesspoint_default(handle);
			main_region_Offline_react(handle, 0);
			transitioned_after = 0;
		}  else
		{
			if (handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_SetTopic_time_event_0_raised == bool_true)
			{ 
				exseq_main_region_Offline_r1_SetTopic(handle);
				react_main_region_Offline_r1__choice_3(handle);
				transitioned_after = 0;
			} 
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Offline_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_r1_Entry_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Entry. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_Entry_time_event_0_raised == bool_true)
		{ 
			exseq_main_region_Offline_r1_Entry(handle);
			sc_observable_next(&handle->ifaceWizFi360.setStationMode);
			handle->ifaceWizFi360.setStationMode_raised = bool_true;
			enseq_main_region_Offline_r1_SetStationMode_default(handle);
			main_region_Offline_react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Offline_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_r1_SetStationMode_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state SetStationMode. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Offline_r1_SetStationMode(handle);
			sc_observable_next(&handle->ifaceWizFi360.enableDhcp);
			handle->ifaceWizFi360.enableDhcp_raised = bool_true;
			enseq_main_region_Offline_r1_EnableDhcp_default(handle);
			main_region_Offline_react(handle, 0);
			transitioned_after = 0;
		}  else
		{
			if (handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_SetStationMode_time_event_0_raised == bool_true)
			{ 
				exseq_main_region_Offline_r1_SetStationMode(handle);
				react_main_region_Offline_r1__choice_0(handle);
				transitioned_after = 0;
			} 
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Offline_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_r1_ConfigureMqtt_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ConfigureMqtt. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Offline_r1_ConfigureMqtt(handle);
			sc_observable_next(&handle->ifaceWizFi360.setTopic);
			handle->ifaceWizFi360.setTopic_raised = bool_true;
			enseq_main_region_Offline_r1_SetTopic_default(handle);
			main_region_Offline_react(handle, 0);
			transitioned_after = 0;
		}  else
		{
			if (handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_ConfigureMqtt_time_event_0_raised == bool_true)
			{ 
				exseq_main_region_Offline_r1_ConfigureMqtt(handle);
				react_main_region_Offline_r1__choice_2(handle);
				transitioned_after = 0;
			} 
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Offline_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_r1_EnableDhcp_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state EnableDhcp. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->current.ifaceWizFi360.ok_raised == bool_true)
		{ 
			exseq_main_region_Offline_r1_EnableDhcp(handle);
			sc_observable_next(&handle->ifaceWizFi360.configureMqtt);
			handle->ifaceWizFi360.configureMqtt_raised = bool_true;
			enseq_main_region_Offline_r1_ConfigureMqtt_default(handle);
			main_region_Offline_react(handle, 0);
			transitioned_after = 0;
		}  else
		{
			if (handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_EnableDhcp_time_event_0_raised == bool_true)
			{ 
				exseq_main_region_Offline_r1_EnableDhcp(handle);
				react_main_region_Offline_r1__choice_1(handle);
				transitioned_after = 0;
			} 
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Offline_react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Offline_r1_ConnectToAccesspoint_react(MqttClientStatemachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ConnectToAccesspoint. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->current.ifaceWizFi360.ok_raised) == bool_true) && ((handle->ifaceWizFi360.wifiConnected) == bool_true))
		{ 
			exseq_main_region_Offline_r1_ConnectToAccesspoint(handle);
			react_main_region_Offline_r1_WifiConnectionEstablished(handle);
			transitioned_after = 0;
		}  else
		{
			if (((handle->current.ifaceWizFi360.fail_raised) == bool_true) && ((!handle->ifaceWizFi360.wifiConnected) == bool_true))
			{ 
				exseq_main_region_Offline_r1_ConnectToAccesspoint(handle);
				sc_observable_next(&handle->ifaceWizFi360.connectToAccessPoint);
				handle->ifaceWizFi360.connectToAccessPoint_raised = bool_true;
				handle->ifaceWizFi360.wifiFailCounter += 1;
				enseq_main_region_Offline_r1_ConnectToAccesspoint_default(handle);
				main_region_Offline_react(handle, 0);
				transitioned_after = 0;
			}  else
			{
				if ((handle->ifaceWizFi360.wifiFailCounter) == (3))
				{ 
					exseq_main_region_Offline_r1_ConnectToAccesspoint(handle);
					react_main_region_Offline_r1__choice_4(handle);
					transitioned_after = 0;
				}  else
				{
					if (handle->current.timeEvents.MqttClientStatemachine_main_region_Offline_r1_ConnectToAccesspoint_time_event_0_raised == bool_true)
					{ 
						exseq_main_region_Offline_r1_ConnectToAccesspoint(handle);
						react_main_region_Offline_r1__choice_4(handle);
						transitioned_after = 0;
					} 
				}
			}
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = main_region_Offline_react(handle, transitioned_before);
	} return transitioned_after;
}




